### ISSUE TITLE
Connect Backend and Frontend

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhysInfo/altklausur-ausleihe#14]

**Comment by TomTomRixRix** [comment]
First development is done on branch `further-frontend`. Requesting all exams already works. Requesting individual, watermarked exams is still to be done.

**Comment by TomTomRixRix** [comment]
This should be done now. Please have a go and test this @christian-heusel. Feel free to close this issue if you think that all connections between frontend and backend have been implemented.
