### ISSUE TITLE
Redirect works only the first time

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhysInfo/altklausur-ausleihe#21]
Steps to reproduce:
1. Go to the moodle link
2. Get redirected to https://altklausuren.mathphys.info/app/exams
3. press F5
4. Get a 404

**Comment by TomTomRixRix** [comment]
Should be solved in the nginx config. See here for details: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
