### ISSUE TITLE
Disable downloadbutton in preview Iframe

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhysInfo/altklausur-ausleihe#43]
The download button in the IFrame could be disabled. Maybe this removes nices features so will just checkt it out.

https://stackoverflow.com/questions/41586093/disable-hide-download-button-in-iframe-on-default-pdf-viewer

**Comment by TomTomRixRix** [comment]
Interestingly, I neither have a download button in my iframe PDF viewer in Firefox, nor in Safari. So I guess this is highly platform dependent and might not be worth putting much effort into.

**Comment by christian-heusel** [comment]
Feel free to close as wontfix 😊
