### ISSUE TITLE
Translate texts from German to English

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhysInfo/altklausur-ausleihe#53]
On branch `multilingual` internationalization was implemented enabling the switching between languages within the application. However, the texts themselves still need to be translated properly. To do so, the content of [file en.json](https://github.com/FachschaftMathPhysInfo/altklausur-ausleihe/blob/multilingual/frontend/src/locales/en.json) needs to be updated.

**Comment by josephholten** [comment]
I will be working on this issue in the coming days. Have already started translating

**Comment by josephholten** [comment]
I would change "student representatives" in impress.intro to "student body" - that seems to be the more correct translation of "Fachschaft". Student representatives would in German be more like "Studentenvertreter".

I have a few general comments: 
- header4 has a typo in german: whitespace after "/"
- "zugangsdaten" subheader is missing a new line
- I would - in german and in english - consistenly refer to altklausuren.mathphys.info as "the platform". I have seen similar formulations in other legal documents like AGB's and imprints

**Comment by christian-heusel** [comment]
I am not really a codeowner for this part of the project, but I'd assume you are also free to change the names, just make sure to change their occurences in the `.vue` source files 😊

**Comment by josephholten** [comment]
I only meant in the user facing text in the imprint - the part I'd be working on first but thanks for the orientation

**Comment by wipplingermax** [comment]
First translation added in fc52330
