### ISSUE TITLE
Preview not working on mobile

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhysInfo/altklausur-ausleihe#59]
Atleast on my phone with "Samsung Internet" as browser the preview via IFrame is not working!
Instead the viewer suggests downloading the file and opening it separately ...

Maybe we should

a) Disable preview on mobile?
b) Wait for Issue #44 and use images for preview?
c) ...?

**Comment by TomTomRixRix** [comment]
Probably `:show-expand="!isMobile"` in the data table and 
```javascript 
isMobile() {
      return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        navigator.userAgent
      );
    },
```
in the methods of ExamList might solve this issue.
