### ISSUE TITLE
Ex und Theo Altklausuren

### ISSUE THREAD

**Issue by ChrisBtt** [FachschaftMathPhysInfo/altklausur-ausleihe#89]
Soweit ich weiß haben Norbert Frank für die Ex I+II zugestimmt sowie Bartelmann für Theo oder? Dann können die Klausuren da noch rein. 
Wenn die Einverständniserklärungen gebraucht werden, gerne Nachricht an mich. Dann such ich die raus.

**Comment by christian-heusel** [comment]
A.M. [11/02/2022 15:52]
Soeben sind zwei Einwilligungen aus der Physik dazugekommen (Bartelmann und Frank)
