### ISSUE TITLE
Add meta tag into pdf document for higher safety

### ISSUE THREAD

**Issue by ChrisBtt** [FachschaftMathPhysInfo/altklausur-ausleihe#91]
For higher safety, the meta data in the pdf file can be adjusted beside the watermark in the pdf file.

Zum Beispiel: 
exiftool -Title="This is the Title" -Author="Happy Man" -Subject="PDF Metadata" drawing.pdf

**Comment by christian-heusel** [comment]
Already implemented in a different fashion in #88!
